baseurl = "https://petermalmgren.com/"
languageCode = "en-us"
title = "Peter Malmgren"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsUseClasses = true

[pygmentsOptions]
    linenos = "table"

staticDir = ["static"]

[taxonomies]
    category = "categories"
    project = "projects"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[mediaTypes]
    [mediaTypes."text/css"]
        suffixes = ["css"]
